config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  root to: 'pages#home'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [ :edit, :update, :show ]
  resources :meals do
    resources :meetings, only: [ :create, :index, :update ] do
      resources :reviews, only: [ :new, :create ]
    end
  end
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :meal
  belongs_to :user
  has_many :reviews
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  def create
    meal = Meal.find(params[:meal_id])
    meeting = Meeting.new(status: "Pending")
    meeting.user = current_user
    meeting.meal = meal
    meeting.save
    redirect_to meal_meetings_path
  end

  def index
    @guest_meetings = Meeting.where(user_id: current_user.id)
    @host_meetings = Meeting.joins(:meal => :user).where(:users => {:id => current_user.id})
    @my_meals = current_user.meals.sort_by(&:date)
    @my_meetings = @guest_meetings.sort_by do |meeting|
      Meal.find(params[:meal_id]).date
    end
  end

  def update
    @host_meeting = Meeting.find(params[:id])
    @host_meeting.status = params["status"]
    @host_meeting.save
    redirect_to meal_meetings_path
  end

  private

  def meeting_params
    params.require(:meeting).permit(:user_id, :meal_id, :status)
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/index.html.erb
<h1 class="text-center">My dates</h1>
  <br>
<div class="tabs">
  <a class="tab active" data-target="#host">
    <h3>Host</h3>
    <p><%= @my_meals.count %> dates</p>
  </a>
  <a class="tab" data-target="#guest">
    <h3>Guest</h3>
    <p><%= @guest_meetings.count %> dates</p>
  </a>
</div>
<br>

<div class="container tab-content" id="host">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">

      <% @my_meals.each do |my_meal| %>
      <div class="meeting">
        <div class="img-meeting item medium">
          <% if my_meal.photos? %>
            <%= cl_image_tag my_meal.photos.first.path, height: 100, width: 150, crop: :fill  %>
          <% else %>
            <%= image_tag("plate.jpeg", size: "150x100", alt: "plate")%>
          <% end %>
        </div>
        <div class='meeting-body item mdlarge'>
          <h4><%= link_to my_meal.name.capitalize, meal_path(my_meal) %> </h4>
          <span class="date"><i class="fa fa-calendar" aria-hidden="true"></i> <%= my_meal.date.strftime('%a %d %b %Y') %> </span>
          <p><%= my_meal.description %></p>
        </div>
        <div class="participants item mdlarge">
          <p>Organizer: <%= my_meal.user.first_name %> <%= my_meal.user.last_name %></p>
          <p><%= my_meal.user.email %></p>
        </div>
      </div>
        <div class="row">
          <div class="col-sm-11 col-sm-offset-1">
            <% @host_meetings.each do |meeting| %>
              <% if meeting.meal_id == my_meal.id %>
                <div class="meeting">
                  <div class="img-meeting item medium text-center">
                    <% if meeting.user.photo? %>
                      <%= cl_image_tag meeting.user.photo.path, class: "avatar-large"  %>
                    <% else %>
                      <%= image_tag("default_profile.jpeg", size: "150x100", alt: "plate", class: "avatar-large")%>
                    <% end %>
                    <h4><%= link_to "#{meeting.user.first_name} #{meeting.user.last_name}", user_path(meeting.user) %></h4>
                  </div>
                  <div class='meeting-body item mdlarge text-justify'>
                    <p><%= meeting.user.description %></p>
                  </div>
                  <div class="meeting-status item md text-center">
                    <div class="status">
                      <p>Status: <%= meeting.status %></p>
                      <% if meeting.status == "Pending" %>
                        <i class="fa fa-question" aria-hidden="true"></i>
                        <ul class="list-unstyled">
                          <li><%= button_to("Approve", meal_meeting_path(current_user, meeting), method: :patch, params: { status: "Approved" }, class: "btn btn-success") %></li>
                          <li><%= button_to("Deny", meal_meeting_path(current_user, meeting), method: :patch, params: { status: "Denied" }, class: "btn btn-danger") %></li>
                        </ul>
                      <% elsif meeting.status == "Approved" %>
                        <i class="fa fa-check" aria-hidden="true"></i>
                      <% else %>
                        <i class="fa fa-times" aria-hidden="true"></i>
                      <% end %>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<br>

<div class="container tab-content hidden" id="guest">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <% @my_meetings.each do |meeting| %>
        <div class="meeting">
          <div class="meeting-status item small">
            <div class="status">
              <p>Status: <%= meeting.status %></p>
              <% if meeting.status == "Pending" %>
                <i class="fa fa-question" aria-hidden="true"></i>
              <% elsif meeting.status == "Approved" %>
                <i class="fa fa-check" aria-hidden="true"></i>
              <% else %>
                <i class="fa fa-times" aria-hidden="true"></i>
              <% end %>
            </div>
          </div>
          <div class="img-meeting item medium">
            <% if meeting.meal.photos? %>
              <%= cl_image_tag meeting.meal.photos.first.path, height: 100, width: 150, crop: :fill %>
            <% else %>
              <%= image_tag("plate.jpeg", size: "150x100", alt: "plate")%>
              <% end %>
          </div>
          <div class='meeting-body item mdlarge'>
          <h4><%= link_to meeting.meal.name, meal_path(meeting.meal) %> </h4>
            <span><i class="fa fa-calendar" aria-hidden="true"></i> <%= meeting.meal.date.strftime('%a %d %b %Y') %> </span>
            <p><%= meeting.meal.description %></p>
          </div>
          <div class="participants item mdlarge">
            <p>Organizer: <%= meeting.meal.user.first_name %> <%= meeting.meal.user.last_name %></p>
            <p>Guest: <%= meeting.user.email %> <%= meeting.user.last_name %></p>
              <% if meeting.status == "Approved" && Review.where(meeting_id: meeting.id, reviewer: current_user.id).count == 0 %>
              <%= link_to "Review this person", new_meal_meeting_review_path(:meeting_id => meeting.id), class: "btn btn-info" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
</br>

<% content_for(:after_js) do %>
  <% javascript_tag do %>
    $(function(){

    $(".tab").on("click", function(e){
      $(".tab").removeClass('active');
      $(this).addClass('active');
      $(".tab-content").addClass('hidden');
      $($(this).data('target')).removeClass('hidden');
    });

  });
  <% end %>
<% end %>