config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  root to: 'pages#home'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [ :edit, :update, :show ]
  resources :meals do
    resources :meetings, only: [ :create, :index, :update ] do
      resources :reviews, only: [ :new, :create ]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :meals, dependent: :destroy
  has_attachment :photo
  has_many :meetings, through: :meals
  has_many :meetings
  has_many :reviews

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: [:facebook]
  # validates :first_name, presence:true
  # validates :last_name, presence:true
  # validates :gender, presence:true, inclusion: {in: ["Male", "Female"], message: "%{value} is not a valid gender" }
  # validates :photo, presence:true
  # validates :description, presence:true
  validates :email, presence:true

  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def edit
    # raise
    if params[:id].to_i == current_user.id
      @user = current_user
    else
      flash[:alert] = 'Nice try! - This is nor your profile...'
      redirect_to :root
    end
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :description, :age, :gender, :photo, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="page-container">
  <div class="row">
    <h1>Tell us more about you !</h1>
      <%= render "shared/form" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="col-xs-12 col-sm-6">
    <div class="row">
      <div class="col-xs-12">
        <div class="row">
          <div class="user-photo text-center">
           <% if @user.photo? %>
              <%= cl_image_tag @user.photo.path, width: 300, height: 300, crop: :fill, class:"avatar-polaroid" %>
            <% else %>
              <%= image_tag "default_profile.jpg", width: 300, height: 300, crop: :fill, class:"avatar-polaroid"%>
            <% end %><br><br>
            <% @user.reviews.average(:star).to_i.times do %>
              <i class="fa fa-star" style="color: #ffb400"></i>
            <% end %><br><br>
            <% if user_signed_in? && current_user == @user %>
              <em><%= link_to "Edit my profile", edit_user_path(current_user) %></em>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <div class="user-information text-center">
              <h1><%= "#{@user.first_name} #{@user.last_name}"%> </h1>
              <p>Age: <%= @user.age %></p>
              <p>Gender: <%= @user.gender %></p>
               <p class="text-justify" id="user-description">Description: <%= @user.description %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 profile-info">
        <div class="row">
        <h2 class="text-center">Reviews</h2>
        <% if @user.reviews.count != 0 %>
          <% @user.reviews.each do |review| %>
            <div class="col-sm-12">
              <div class="meeting">
                <div class="meeting-status">
                  <div class="status col-xs-3">
                    <% writer = User.find(review.reviewer) %>
                    <% if writer.photo? %>
                      <%= cl_image_tag writer.photo.path, height: 50, width: 75, crop: :fill  %>
                    <% else %>
                      <%= image_tag("default_profile.jpeg", size: "75x50", alt: "profile", class: "avatar")%>
                    <% end %>
                    <h4><%= writer.first_name %> <%= writer.last_name %></h4>
                    </div>
                  <div class="img-meeting col-xs-4">
                    <% review.star.to_i.times do %>
                      <i class="fa fa-star" style="color: #ffb400"></i>
                    <% end%>
                  </div>
                  <div class='meeting-body col-xs-5'>
                    <p><%= review.content %></p>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <div class="col-sm-12">
            <p style="color: red"><%= @user.first_name %> <%= @user.last_name %> has no review yet</p>
          </div>
        <% end %>
        </div>
        <div class="col-sm-12">
          <div class="row">
            <h2 class="text-center">Meals</h2>
            <br>
            <% if @user.meals.count != 0 %>
              <% @user.meals.each do |meal| %>
                <div class="listing-card-wrapper col-sm-6">
                  <% if meal.photos? %>
                    <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path meal.photos.first.path, height: 175, width: 360, crop: :fill; %>');">
                  <% else %>
                    <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://lewagon.github.io/ui-components/images/card-background.jpeg');">
                  <% end %>
                    <div class="card-category"><%= meal.city %></div>
                    <div class="card-description">
                      <h2><%= meal.user.first_name %></h2>
                      <p><%= meal.name %></p>
                      <%= link_to "", meal_path(meal), class: "card-link" %>
                    </div>
                  </div>
                </div>
              <% end %>
            <% else %>
              <p style="color: red"><%= @user.first_name %> <%= @user.last_name %> has no meal yet</p>
            </div>
          </div>
        <% end %>
        </div>
      </div>
</div>