config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  root to: 'pages#home'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [ :edit, :update, :show ]
  resources :meals do
    resources :meetings, only: [ :create, :index, :update ] do
      resources :reviews, only: [ :new, :create ]
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="footer-content col-xs-12 col-sm-10 col-sm-offset-1">
          <ul class="list-inline">
            <li>
              <a href="#"><i class="fa fa-youtube"></i></a>
            </li>
            <li>
              <a href="#"><i class="fa fa-instagram"></i></a>
            </li>
            <li>
              <a href="#"><i class="fa fa-facebook"></i></a>
            </li>
            <li>
              <a href="#"><i class="fa fa-twitter"></i></a>
            </li>
          </ul>
          <p>Made with fucking ♥ by (m)eat-me Team.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_form.html.erb
<div class="col-xs-12 col-md-offset-3 col-md-6">
  <div class="simple_form_for">

    <%= simple_form_for @user do |f| %>
      <div class="row">
        <div class="col-xs-12 col-sm-6">
          <%= f.input :first_name, label_input: "First Name", required: true %>
        </div>
        <div class="col-xs-12 col-sm-6">
          <%= f.input :last_name, label_input: "Last Name", required: true %>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12 col-sm-4">
          <%= f.input :phone_number %>
        </div>
        <div class="col-xs-12 col-sm-4">
          <%= f.input :age, required: true %>
        </div>
        <div class="col-xs-12 col-sm-4">
          <%= f.input :gender, required: true,  collection: [ ["Male", "Male"], ["Female", "Female"] ], label_method: :last, value_method: :first, as: :radio_buttons %>
        </div>
      </div>

        <div class="col-xs-12  col-sm-6">
           <%= f.input :photo, as: :attachinary %>
        </div>

      <div class="row">
        <div class="col-xs-12  col-sm-6">
          <%= f.input :email, required: true %>
        </div>

    </div>

      <%= f.input :description, label_input: "About me", :input_html => {:rows => 10} %>
      <%= f.button :submit, class:"btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/shared/_login.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <div class="facebook-connect">
        <%= render "devise/shared/links" %>
      </div>
      <div class="signup-or-separator">
          <span class="h6 signup-or-separator--text">or</span>
          <hr>
      </div>
      <div class="signup-form">
        <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">
            <div class="form-group">
              <div class="input-group">
              <div class="input-group-addon"><i class="fa fa-envelope-o" aria-hidden="true"></i></div>
                <%= f.input :email, required: false, autofocus: true, label: false, placeholder: "Email" %>
              </div>
            </div>
            <div class="form-group">
              <div class="input-group">
              <div class="input-group-addon"><i class="fa fa-lock" aria-hidden="true"></i></div>
                <%= f.input :password, required: false, label: false, placeholder: "Password" %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="form-actions">
          <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
            </div>
          </div>

        <div class="form-actions">
          <%= f.button :submit, "Log in", class: "btn btn-danger", style: "width: 100%" %>
        </div>
        <% end %>
      </div>
      <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
      <hr>
      <div class="already-member">
          <p>Don’t have an account?</p>
          <%= link_to "Sign up", new_registration_path(resource_name), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div id="navbar">
  <div class="navbar-wagon" >
    <!-- Logo -->
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "burger_heart.png" %>
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">


      <!-- Different navigation if login or not -->
      <% if user_signed_in? %>


        <!-- Profile picture and dropdown -->
        <div class="navbar-wagon-item">
          <div class="dropdown">
           <% if current_user.photo? %>
            <%= cl_image_tag current_user.photo.path, width: 30, height: 30, crop: :fill,gravity: :face, class: "avatar dropdown-toggle", "data-toggle" => "dropdown", id: "navbar-wagon-menu" %>
            <% else %>
              <%= image_tag "default_profile.jpg", width: 30, height: 30, crop: :fill, class: "avatar dropdown-toggle", "data-toggle" => "dropdown", id: "navbar-wagon-menu "%>
            <% end %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to root_path do %>
                  <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
                <% end %>
              </li>
              <li>
                <%= link_to user_path(current_user) do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to meal_meetings_path(current_user) do %>
                  <i class="fa fa-cutlery"></i> <%= t(new_user_registration_path, default: "My dates") %>
                <% end %>
              </li>
              <li>
                <%= link_to new_meal_path do %>
                  <i class="fa fa-cutlery"></i> <%= t(new_user_registration_path, default: "Create my meal") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>

      <% else %>

        <!-- Login text link -->
        <%= link_to t(".sign_in", default: "Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <% end %>

    </div>

    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Some mobile link</a></li>
          <li><a href="#">Other one</a></li>
          <li><a href="#">Other one</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<% content_for(:js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var navbar = $(".navbar-wagon");
      $(window).on("scroll", function(e) {
      var scroll = $(window).scrollTop();
        if (scroll > 450) {
          navbar.addClass("navbar-fixed-top", 5000);
        } else {
          navbar.removeClass("navbar-fixed-top", 5000);
        }
      });
    });
  <% end %>
<% end %>

app/views/shared/_signup.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <div class="facebook-connect">
      </div>
      <div class="signup-or-separator">
          <span class="h6 signup-or-separator--text">or</span>
          <hr>
      </div>
      <div class="signup-form">
        <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">
            <div class="form-group">
              <div class="input-group">
              <div class="input-group-addon"><i class="fa fa-envelope-o" aria-hidden="true"></i></div>
              <%= f.input :email, required: true, autofocus: true, placeholder: 'Email', label: false, class: "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <div class="input-group">
              <div class="input-group-addon"><i class="fa fa-lock" aria-hidden="true"></i></div>
              <%= f.input :password, required: true, placeholder: 'Password', label: false %>
              <%= f.input :password_confirmation, placeholder: 'Confirm password', label: false, required: true %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="form-actions">
              <%= f.button :submit, "Sign up", class: "btn btn-danger", style: "width: 100%" %>
            </div>
          </div>
        <% end %>
      </div>
      <hr>
      <div class="already-member">
          <p>Already a (m)eat me member?</p>
          <%= link_to "Log in", new_session_path(resource_name), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>