config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  root to: 'pages#home'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [ :edit, :update, :show ]
  resources :meals do
    resources :meetings, only: [ :create, :index, :update ] do
      resources :reviews, only: [ :new, :create ]
    end
  end
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user
  has_many :meetings

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  has_attachments :photos, maximum: 5
  validates :name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :description, presence: true
  validates :food_type, presence: true
  validates :meeting_type, presence: true
  validates :date, presence: true

  validate :expiration_date_cannot_be_in_the_past

  def expiration_date_cannot_be_in_the_past
    if date < Date.today
      errors.add(:expiration_date, "can't be in the past")
    end
  end

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: [ :show, :edit, :update ]
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @meals = search(params[:gender], params[:food_type]).paginate(:page => params[:page], :per_page => 10).order('id DESC')
    @meals_map = @meals.where.not(latitude: nil, longitude: nil)
    @hash = Gmaps4rails.build_markers(@meals_map) do |meal, marker|
      marker.lat meal.latitude
      marker.lng meal.longitude
      marker.infowindow render_to_string(partial: "/meals/info_window", locals: { meal: meal })
    end
  end


  def gmaps4rails_infowindow
      puts "this is a test"
  end


  def show
    @user = @meal.user
    if !@meal.latitude.nil? && !@meal.longitude.nil?
      @hash = Gmaps4rails.build_markers([@meal]) do |meal, marker|
        marker.lat meal.latitude
        marker.lng meal.longitude
        marker.infowindow render_to_string(partial: "/meals/info_window", locals: { meal: meal })
      end
    end
  end

  def new
      @meal = Meal.new
  end

  def edit
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.user = current_user
    if @meal.save
      flash[:notice] = 'meal was successfully created'
      redirect_to meal_path(@meal)
    else
      render :new
    end
  end

  def update
    if @meal.update(meal_params)
      flash[:notice] = 'meal was successfully updated'
      redirect_to @meal
    else
      render :edit
    end
  end

 private

  def set_meal
    @meal = Meal.find(params[:id])
  end

  def meal_params
    params.require(:meal).permit(:user_id, :name, :address, :city,  :date, :description, :food_type, :price, :meeting_type, :latitude, :longitude, photos: [])
  end

  def search(gender, food_type)
    if food_type.nil?
      Meal.all
    elsif gender == "whatever" && food_type == "all"
      Meal.all
    elsif gender != "whatever" && food_type == "all"
      Meal.joins(:user).where(:users => {:gender => "#{gender.capitalize}"})
    elsif gender == "whatever" && food_type != "all"
      Meal.where(food_type: "#{params[:food_type].capitalize}")
    else
      Meal.joins(:user).where(food_type: "#{food_type.capitalize}", :users => {:gender => "#{gender.capitalize}"})
    end
  end
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/meals/_info_window.html.erb
<div class="info-window">
  <div class="text-center">
    <% if meal.photos? %>
        <%= link_to (cl_image_tag meal.photos.first.path, width: 260, height: 126, crop: :fill), meal_path(meal) %>
    <% else %>
        <%= link_to (image_tag asset_path('default_card.jpg'), width: 260, height: 126, crop: :fill), meal_path(meal) %>
    <% end %>
  </div>
  <h3><%= link_to "#{meal.food_type} food", meal_path(meal) %></h3>
  <div class="info-content">
    <div class="info-avatar"><% if meal.user.photo? %>
            <%= cl_image_tag meal.user.photo.path, height: 30, width: 30, crop: :fill, gravity: :face, class: "card-user avatar" %>
          <% else %>
            <%= image_tag "default_profile.jpg", class: "avatar" %>
          <% end %>
    </div>
    <div class="info-user"><%= meal.user.first_name %></div>
    <div class="info-rating"><% meal.user.reviews.average(:star).to_i.times do %>
          <i class="fa fa-star" style="color: #ffb400"></i>
        <% end %></div>
  </div>
</div>

app/views/meals/edit.html.erb
<div class="container">
  <div class="row">
  <h2>Veuillez mettre à jour les informations, ci-dessous:</h2>
  <div class="form-inputs">
    <div class="col-sm-offset-4 col-sm-4"><%= simple_form_for(@meal) do |f| %>
  <%= f.error_notification %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :city %>
    <%= f.input :date %>
    <%= f.input :price, label_input:"Price in €", input_html: {value: f.object.price || '1'} %>
    <%= f.input :description %>
    <%= f.input :food_type %>
    <%= f.input :meeting_type %>
    <%= f.input :photos, as: :attachinary %>

    <div class="form-actions">
    <%= f.button :submit %>
   </div>
   <%= link_to 'Back', meals_path, class: "btn btn-primary" %>
  <% end %>
  </div>
    </div>
  </div>
</div>

app/views/meals/index.html.erb
<p id="notice"><%= notice %></p>
<div class="search">
  <div class="search-sidebar">
    <div class="search-box">
      <h3><%= @meals.length %> meal(s) found for:</h3>
      <form class="form-inline" action="/meals" method="GET">
        <div class="input-group">
          <span class="input-group-addon" id="basic-addon1">I want to (m)eat </span>
          <select name="gender" class="form-control input-lg">
            <option value="whatever" selected><%= params[:gender]%></option>
            <option value="whatever">anyone</option>
            <option value="female">a woman</option>
            <option value="male">a man</option>
          </select>
          <span class="input-group-addon" id="basic-addon1">and eat</span>
            <select name="food_type" class="form-control input-lg">
              <option value="all" selected><%= params[:food_type]%></option>
              <option value="all">anything...</option>
              <option value="french">french food</option>
              <option value="japanese">japanese food</option>
              <option value="chinese">chinese food</option>
              <option value="indian">indian food</option>
              <option value="italian">italian food</option>
            </select>
        </div>
        <input type="submit" class="btn btn-yours" value="(m)eat someone">
      </form>
    </div>
    <div class="search-results">
      <div class= "row">
        <div class="col-xs-12">
          <div class="row">
            <% @meals.each do |meal| %>
            <div class="listing-card-wrapper col-sm-12 col-md-6 space-4">
              <% if meal.photos? %>
                <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path meal.photos.first.path, height: 175, width: 360, crop: :fill; %>');">
                <% else %>
                <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= asset_path 'default_card.jpg' %>');">
              <% end %>
                <div class="card-category"><%= meal.city %></div>
                <div class="card-description">
                  <h2><%= meal.user.first_name %></h2>
                  <p><%= meal.name %></p>
                </div>
                 <% if meal.user.photo? %>
                    <%= cl_image_tag meal.user.photo.path, height: 30, width: 30, crop: :fill, gravity: :face, class: "card-user avatar" %>
                  <% else %>
                    <%= image_tag "default_profile.jpg", class: "card-user avatar" %>
                  <% end %>
                <%= link_to "", meal_path(meal), class: "card-link" %>
                </div>
                </div>
            <% end %>
            </div>
          </div>
          <div class="search-pagination">
            <div class="pagination-info">
              <%= page_entries_info @posts %>
            </div>
            <%= will_paginate @posts, :container => false %>
          </div>
        </div>
      </div>
  </div>
  <div class="search-map">
    <div id="map" style="width: 100%; height: 100%;"></div>
    </div>
</div>
<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      $('#footer').css('display', 'none');
      $('html, body').css({overflow: 'hidden',height: '100%'});
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>

app/views/meals/new.html.erb
<div class="container padded">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2 text-center">
      <h1>Create a new meal</h1>
      <p>Please, filled the following informations:</p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-offset-4 col-sm-4">
      <%= simple_form_for(@meal) do |f| %>
        <%= f.error_notification %>
          <div class="form-inputs">
          <%= f.input :name, label_input:"Please write a title for your meeting" %>
          <%= f.input :address, id:"meal_address" %>
          <%= f.input :city, collection: ["Paris"], id:"meal_city" %>
          <%= f.input :date %>
          <%= f.input :price, label_input:"Price in €", input_html: {value: f.object.price || '1'} %>
          <%= f.input :description, label_input: "describe your meeting" %>
          <%= f.input :food_type, collection: ["French", "Japanese", "Chinese", "Indian", "Italian"] %>
          <%= f.input :meeting_type, collection: ["Fun", "Professionnal", "Hot"] %>
          <%= f.input :photos, as: :attachinary %>
          <div class="form-actions">
            <%= f.button :submit %>
          </div>
          <%= link_to 'Back', meals_path, class: "btn btn-primary" %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/meals/show.html.erb
<div class="banner-cover-img">
    <div id="my_carousel" class="carousel slide" data-ride="carousel">
    <!-- Bulles -->
    <% if @meal.photos? %>
      <% @meal.photos.each_with_index do |photo, index| %>
        <% if index == 0 %>
          <li data-target="#my_carousel" data-slide-to="0" class="active"></li>
        <% else %>
          <li data-target="#my_carousel" data-slide-to="index"></li>
        <% end %>
      <% end %>
    <% end %>
    <!-- Slides -->
      <div class="carousel-inner">
    <!-- Page 1 -->
      <% if @meal.photos? %>
        <% @meal.photos.each_with_index do |photo, index| %>
          <% if index == 0 %>
             <div class="item active">
                <div class="carousel-page">
                  <div class="img-responsive" style="margin:0px auto; height: 500px;" />
                    <%= cl_image_tag @meal.photos[index].path, width: 1525, height: 400, crop: :fill %>
                  </div>
                </div>
              </div>
          <% else %>
           <div class="item">
              <div class="carousel-page">
                <div class="img-responsive" style="margin:0px auto; height: 500px;" />
                  <%= cl_image_tag @meal.photos[index].path, width: 1525, height: 400, crop: :fill %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <div class="img-responsive" style="margin:0px auto; height: 500px;" />
          <%= image_tag "empty-plate.jpg", height: 400 %>
        </div>
      <% end %>

        <!-- Contrôles -->
      <% if @meal.photos? && @meal.photos.count > 1  %>
        <a class="left carousel-control" href="#my_carousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#my_carousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      <% end %>
      </div>
    </div>
</div>

<div class="container meal-container">
  <div class="row" >
    <!-- DIV PRINCIPALE CENTREE -->
    <div class="col-xs-12 col-sm-6 col-sm-offset-1">
      <div class="header-flat-details">
        <div class="header-meal-presentation">
          <h1><%= @meal.name %> </h1>
          <p><%= @meal.date.strftime('%d/%m/%Y') %> - <%= @meal.city %><%= (@meal.price.to_i > 0) ? " - #{@meal.price} €" : "" %> </p>
          <% if user_signed_in? && current_user.id == @meal.user.id %>
            <%= link_to 'Edit', edit_meal_path(@meal) %>
          <% end %>
        </div>
        <div class="header-meal-host text-center">
          <% if @user.photo? %>
            <%= cl_image_tag @user.photo.path, width: 300, height: 300, crop: :fill, class:"avatar-large img-circle" %>
          <% else %>
             <%= image_tag "default_profile.jpg", width: 300, height: 300, crop: :fill, class:"avatar-large img-circle"%>
          <% end %>
          <p><%= link_to @user.first_name, user_path(@user) %></p>
          <% @user.reviews.average(:star).to_i.times do %>
            <i class="fa fa-star" style="color: #ffb400"></i>
          <% end %>
        </div>
      </div>
      <hr>
      <div class="meal-icons">
        <div class="text-center">
          <i class="fa fa-cutlery" aria-hidden="true"></i><br>
          <%= @meal.food_type %>
        </div>
        <div class="text-center">
          <i class="fa fa-fire" aria-hidden="true"></i><br>
          <%= @meal.meeting_type %>
        </div>
        <div class="text-center">
          <i class="fa fa-bed" aria-hidden="true"></i><br>
          <p>1 Bed</p>
        </div>
      </div>
      <hr>
      <div class="meal-description">
        <h3>More about the dinner</h3>
        <p><%= @meal.description %></p>
      </div>
      <div class="host-description">
        <h3>More about <%= @user.first_name %></h3>
        <p><%= @user.description %></p>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
        <div class="meal-book-box">
          <% if user_signed_in? && current_user.id == @meal.user.id %>
            <h3 class="text-center">Edit this dinner</h3>
            <%= link_to "Edit",edit_meal_path(@meal), class: "btn btn-primary btn-booking", style: "width: 100%" %>
          <% else %>
            <h3 class="text-center">Book this dinner</h3>
            <%= button_to "Book", [@meal, :meetings], class: "btn btn-primary btn-booking",  style: "width: 100%" %>
          <% end %>
        </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <div class="meal-map">
          <h3>Dinner location</h3>
            <div id="map" style="width: 80%; height: 500px;"></div>
        </div>
      </div>
  </div>
</div>
<% content_for(:after_js) do %>
  <script>
    $(document).ready(function() {
      var mealBookBox = $(".meal-book-box");
      $(".banner-cover-img img").attr("width", $(".banner-cover-img").width());
      $(window).on("scroll", function(e) {
        var divHeight = $(".meal-container").height() + 350 - $(".meal-book-box").height();
        var scroll = $(window).scrollTop();
        if (scroll > divHeight) {
          mealBookBox.removeClass("meal-book-box-fixed", 5000);
        } else if (scroll > 450) {
          mealBookBox.addClass("meal-book-box-fixed", 5000);
        } else {
          mealBookBox.removeClass("meal-book-box-fixed", 5000);
        }
      });
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });

    });
  </script>
<% end %>